// Builds a D1 migration that (re)loads the cards of every content/<locale>.json except French,
// which stays as migrated from Supabase.
//   bun scripts/build-content-migration.ts migrations/0002_i18n.sql
import { readdir } from 'node:fs/promises'
import process from 'node:process'

interface Card {
  mode: number
  title: string
  author: string | null
  type: string | null
  cover: string | null
}

const out = process.argv[2]
if (!out)
  throw new Error('usage: bun scripts/build-content-migration.ts <migration.sql>')

const sql = (v: string | number | null) => v === null ? 'NULL' : typeof v === 'number' ? String(v) : `'${v.replaceAll('\'', '\'\'')}'`
const dir = `${import.meta.dir}/../content`
const lines: string[] = []

for (const file of (await readdir(dir)).filter(f => f.endsWith('.json') && f !== 'fr.json').sort()) {
  const { locale, name, guesses } = JSON.parse(await Bun.file(`${dir}/${file}`).text()) as { locale: string, name: string, guesses: Card[] }
  const lang = `(SELECT id FROM langs WHERE locale = ${sql(locale)})`
  lines.push(`\n-- ${name} (${guesses.length} cards)`)
  lines.push(`INSERT INTO langs (name, locale) VALUES (${sql(name)}, ${sql(locale)}) ON CONFLICT(locale) DO UPDATE SET name = excluded.name;`)
  lines.push(`DELETE FROM guesses WHERE lang = ${lang};`)
  for (let i = 0; i < guesses.length; i += 100) {
    const rows = guesses.slice(i, i + 100).map(g => `(${lang}, ${g.mode}, ${sql(g.title)}, ${sql(g.author)}, ${sql(g.type)}, ${sql(g.cover)})`)
    lines.push(`INSERT INTO guesses (lang, mode, title, author, type, cover) VALUES\n${rows.join(',\n')};`)
  }
}

await Bun.write(out, `-- Generated by scripts/build-content-migration.ts from content/*.json. Do not edit by hand.\n${lines.join('\n')}\n`)
console.log(out)
