# Native builds and store submission run on Capgo Cloud Build (see .github/workflows/release.yml).
# fastlane only pushes store screenshots (store/screenshots) and Play graphics (store/play).
#
#   APPLE_KEY_ID=... APPLE_ISSUER_ID=... APPLE_KEY_CONTENT=<base64 p8> fastlane ios screenshots version:3.1.0
#   PLAY_CONFIG_JSON=<base64 service account json> fastlane android screenshots

require "base64"
require "fileutils"
require "tmpdir"

SCREENSHOTS = File.expand_path("../store/screenshots", __dir__)

def stage(locale, mapping)
  dir = Dir.mktmpdir("mimesis-shots")
  mapping.each do |source, target|
    dest = File.join(dir, locale, target)
    FileUtils.mkdir_p(dest)
    Dir[File.join(SCREENSHOTS, source, "*.jpg")].sort.each { |f| FileUtils.cp(f, File.join(dest, "#{source}-#{File.basename(f)}")) }
  end
  dir
end

platform :ios do
  lane :screenshots do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("APPLE_KEY_ID"),
      issuer_id: ENV.fetch("APPLE_ISSUER_ID"),
      key_content: ENV.fetch("APPLE_KEY_CONTENT"),
      is_key_content_base64: true,
    )
    dir = stage("fr-FR", { "ios-6.9" => "", "ipad-13" => "" })
    deliver(
      api_key: api_key,
      app_version: options[:version],
      screenshots_path: dir,
      overwrite_screenshots: true,
      skip_binary_upload: true,
      skip_metadata: true,
      skip_app_version_update: false,
      submit_for_review: false,
      run_precheck_before_submit: false,
      force: true,
    )
  end
end

platform :android do
  lane :screenshots do
    dir = Dir.mktmpdir("mimesis-play")
    dest = File.join(dir, "fr-FR", "images", "phoneScreenshots")
    FileUtils.mkdir_p(dest)
    Dir[File.join(SCREENSHOTS, "android-phone", "*.jpg")].sort.each { |f| FileUtils.cp(f, dest) }
    images = File.join(dir, "fr-FR", "images")
    play = File.expand_path("../store/play", __dir__)
    FileUtils.cp(File.join(play, "icon.png"), File.join(images, "icon.png"))
    FileUtils.cp(File.join(play, "feature-graphic.png"), File.join(images, "featureGraphic.png"))
    upload_to_play_store(
      json_key_data: Base64.decode64(ENV.fetch("PLAY_CONFIG_JSON")),
      metadata_path: dir,
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: false,
      skip_upload_screenshots: false,
    )
  end
end
