-- Initial schema dump from production database
-- This represents the current state of the mimesis database

-- Create enums
CREATE TYPE mode_status AS ENUM ('free', 'paid', 'locked');

-- Create mimesis_lang table
CREATE TABLE IF NOT EXISTS public.mimesis_lang (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    name TEXT NOT NULL,
    locale TEXT NOT NULL UNIQUE
);

-- Create mimesis_modes table
CREATE TABLE IF NOT EXISTS public.mimesis_modes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    name TEXT NOT NULL,
    icon TEXT,
    active BOOLEAN NOT NULL DEFAULT false,
    id_ios TEXT,
    id_android TEXT,
    "order" INTEGER NOT NULL,
    status mode_status NOT NULL DEFAULT 'free'::mode_status
);

-- Create mimesis_users table
CREATE TABLE IF NOT EXISTS public.mimesis_users (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    games INTEGER NOT NULL DEFAULT 0
);

-- Create mimesis_guesses table
CREATE TABLE IF NOT EXISTS public.mimesis_guesses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    lang INTEGER NOT NULL REFERENCES public.mimesis_lang(id),
    mode INTEGER REFERENCES public.mimesis_modes(id),
    author TEXT,
    cover TEXT,
    title TEXT NOT NULL,
    type TEXT
);

-- Create mimesis_games table
CREATE TABLE IF NOT EXISTS public.mimesis_games (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    user_id TEXT REFERENCES public.mimesis_users(id),
    lang INTEGER NOT NULL REFERENCES public.mimesis_lang(id),
    team JSONB NOT NULL,
    mode INTEGER REFERENCES public.mimesis_modes(id),
    found_guess INTEGER[],
    skip_guess INTEGER[]
);

-- Add indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_mimesis_guesses_lang ON public.mimesis_guesses(lang);
CREATE INDEX IF NOT EXISTS idx_mimesis_guesses_mode ON public.mimesis_guesses(mode);
CREATE INDEX IF NOT EXISTS idx_mimesis_games_user_id ON public.mimesis_games(user_id);
CREATE INDEX IF NOT EXISTS idx_mimesis_games_lang ON public.mimesis_games(lang);
CREATE INDEX IF NOT EXISTS idx_mimesis_games_mode ON public.mimesis_games(mode);

-- Enable Row Level Security
ALTER TABLE public.mimesis_lang ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mimesis_modes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mimesis_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mimesis_guesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mimesis_games ENABLE ROW LEVEL SECURITY;

-- Create RLS policies (allowing public read access for guesses, lang, modes)
CREATE POLICY "Allow public read access on mimesis_lang" 
    ON public.mimesis_lang FOR SELECT 
    USING (true);

CREATE POLICY "Allow public read access on mimesis_modes" 
    ON public.mimesis_modes FOR SELECT 
    USING (true);

CREATE POLICY "Allow public read access on mimesis_guesses" 
    ON public.mimesis_guesses FOR SELECT 
    USING (true);

-- Users can insert their own records
CREATE POLICY "Users can insert their own records" 
    ON public.mimesis_users FOR INSERT 
    WITH CHECK (true);

CREATE POLICY "Users can update their own records" 
    ON public.mimesis_users FOR UPDATE 
    USING (true);

CREATE POLICY "Users can read their own records" 
    ON public.mimesis_users FOR SELECT 
    USING (true);

-- Games policies
CREATE POLICY "Users can insert their own games" 
    ON public.mimesis_games FOR INSERT 
    WITH CHECK (true);

CREATE POLICY "Users can read their own games" 
    ON public.mimesis_games FOR SELECT 
    USING (true);
